attempted fix of racey TestStoreOpsCompactionForce test
Seeing a travis-CI test failure, apparently due to raciness...

    https://travis-ci.org/couchbase/moss/builds/133825701

    --- FAIL: TestStoreOpsCompactionForce (0.00s)
        store_test.go:344: expected persistence progress
        store_test.go:350: expected some persistence
    FAIL

I don't actually see this issue on my OSX dev environment, so I don't
know for sure if this is the real fix, hence the "attempted" verbiage.

Change-Id: I6ba8fe49a02352f49c11e94f16096bf36bf369c1
Reviewed-on: http://review.couchbase.org/64567
Reviewed-by: Marty Schoch <marty.schoch@gmail.com>
Tested-by: Steve Yen <steve.yen@gmail.com>