iteratorSingle handles deletions correctly
While running unit tests, I saw an rare instance of this unit test
failure...

    --- FAIL: TestOpsAsyncMergeBatchSize1 (0.00s)
    collection_test.go:592: itr, testi: 81,
     test: struct { op string; k string; v string; expErr error }
           {op:"itr", k:"_:_", v:"+b=BBB,+f=F", expErr:error(nil)},
           expEntries: [+b=BBB +f=F], gotEntries: [+b=BBB -d= +f=F]

The theory is that the background merger goroutine rarely,
occasionally wins some concurrency race, and merges all segments into
a single level.

Then the iterator test code runs next, and that therefore goes through
the iteratorSingle codepaths.

The iteratorSingle was not handling deletion ops correctly (it should
have skipped them).

Change-Id: Ie5ad8ba1e5551bb979924a1866d396ae6d45ab0f
Reviewed-on: http://review.couchbase.org/68256
Reviewed-by: Marty Schoch <marty.schoch@gmail.com>
Tested-by: Steve Yen <steve.yen@gmail.com>